name: mgxevo
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.10
  - perl
  - ipython
  - ipykernel
  - ipywidgets
  - jupyterlab
  - tqdm
  - pandas
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - scikit-learn
  - pip:
    - HTseq
    - ete3
    - plotly
    - biopython
  - agat
  - bowtie2
  - iqtree
  - usher
  - vsearch
  - diamond
  - gblocks
  - vcflib
  - kraken2=2.0.8_beta
  - bracken
  - lftp
  - r-base
  - r-irkernel
  - r-dplyr
  - r-dbplyr
  - r-data.table
  - r-rsqlite
  - r-stringr
  - r-tidyverse
  - r-r.utils
  - r-ggplot2
  - r-hmisc
  - r-wesanderson
  - r-ggbeeswarm
  - r-patchwork
  - r-phytools
  - r-ape
  - r-stringi
  - r-stringdist
  - r-phangorn
  - r-lme4
  - r-lmerTest
  - r-glmnet
  - r-biocmanager
  - r-qlcmatrix
  - r-ggrepel
  - r-gtools
  - r-hues
  - r-argparse
  - bioconductor-ggtree
